# Generated by Django 5.1.4 on 2024-12-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo_url', models.URLField()),
                ('job_location', models.CharField(max_length=255)),
                ('details_page_url', models.URLField()),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('posted_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('employment_type', models.CharField(max_length=50)),
                ('work_from_home_availability', models.BooleanField(default=False)),
                ('is_remote', models.BooleanField(default=False)),
                ('summary', models.TextField()),
                ('employer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('easy_apply', models.BooleanField(default=False)),
                ('willing_to_sponsor', models.BooleanField(default=False)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
