# Generated by Django 5.1.4 on 2024-12-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_summary_job_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='client_brand_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_recent',
        ),
        migrations.RemoveField(
            model_name='job',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='position_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='score',
        ),
        migrations.AddField(
            model_name='job',
            name='company_logo_url_optimized',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_page_url',
            field=models.URLField(blank=True, default='http://example.com/company', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.CharField(blank=True, default='Unknown Location', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='summary',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(default='http://example.com'),
        ),
        migrations.AlterField(
            model_name='job',
            name='details_page_url',
            field=models.URLField(default='http://example.com/details'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer_type',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, default='Unknown Location', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='workplace_types',
            field=models.CharField(blank=True, default='Remote', max_length=100, null=True),
        ),
    ]
