# Generated by Django 5.1.4 on 2024-12-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_client_brand_id_remove_job_culture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='details_page_url',
            field=models.URLField(blank=True, default='http://example.com/details', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_location',
            field=models.CharField(blank=True, default='Unknown Location', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.TextField(blank=True, default='No description available', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True, default='http://example.com', null=True),
        ),
    ]
